// @generated by protoc-gen-es v1.3.0
// @generated from file api/v2/shortcut_service.proto (package slash.api.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { RowStatus } from "./common_pb.js";

/**
 * @generated from enum slash.api.v2.Visibility
 */
export declare enum Visibility {
  /**
   * @generated from enum value: VISIBILITY_UNSPECIFIED = 0;
   */
  VISIBILITY_UNSPECIFIED = 0,

  /**
   * @generated from enum value: PRIVATE = 1;
   */
  PRIVATE = 1,

  /**
   * @generated from enum value: WORKSPACE = 2;
   */
  WORKSPACE = 2,

  /**
   * @generated from enum value: PUBLIC = 3;
   */
  PUBLIC = 3,
}

/**
 * @generated from message slash.api.v2.Shortcut
 */
export declare class Shortcut extends Message<Shortcut> {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: int32 creator_id = 2;
   */
  creatorId: number;

  /**
   * @generated from field: int64 created_ts = 3;
   */
  createdTs: bigint;

  /**
   * @generated from field: int64 updated_ts = 4;
   */
  updatedTs: bigint;

  /**
   * @generated from field: slash.api.v2.RowStatus row_status = 5;
   */
  rowStatus: RowStatus;

  /**
   * @generated from field: string name = 6;
   */
  name: string;

  /**
   * @generated from field: string link = 7;
   */
  link: string;

  /**
   * @generated from field: string title = 8;
   */
  title: string;

  /**
   * @generated from field: repeated string tags = 9;
   */
  tags: string[];

  /**
   * @generated from field: string description = 10;
   */
  description: string;

  /**
   * @generated from field: slash.api.v2.Visibility visibility = 11;
   */
  visibility: Visibility;

  /**
   * @generated from field: slash.api.v2.OpenGraphMetadata og_metadata = 12;
   */
  ogMetadata?: OpenGraphMetadata;

  constructor(data?: PartialMessage<Shortcut>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.Shortcut";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Shortcut;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Shortcut;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Shortcut;

  static equals(a: Shortcut | PlainMessage<Shortcut> | undefined, b: Shortcut | PlainMessage<Shortcut> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.OpenGraphMetadata
 */
export declare class OpenGraphMetadata extends Message<OpenGraphMetadata> {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: string image = 3;
   */
  image: string;

  constructor(data?: PartialMessage<OpenGraphMetadata>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.OpenGraphMetadata";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OpenGraphMetadata;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OpenGraphMetadata;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OpenGraphMetadata;

  static equals(a: OpenGraphMetadata | PlainMessage<OpenGraphMetadata> | undefined, b: OpenGraphMetadata | PlainMessage<OpenGraphMetadata> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.ListShortcutsRequest
 */
export declare class ListShortcutsRequest extends Message<ListShortcutsRequest> {
  constructor(data?: PartialMessage<ListShortcutsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.ListShortcutsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListShortcutsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListShortcutsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListShortcutsRequest;

  static equals(a: ListShortcutsRequest | PlainMessage<ListShortcutsRequest> | undefined, b: ListShortcutsRequest | PlainMessage<ListShortcutsRequest> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.ListShortcutsResponse
 */
export declare class ListShortcutsResponse extends Message<ListShortcutsResponse> {
  /**
   * @generated from field: repeated slash.api.v2.Shortcut shortcuts = 1;
   */
  shortcuts: Shortcut[];

  constructor(data?: PartialMessage<ListShortcutsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.ListShortcutsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListShortcutsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListShortcutsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListShortcutsResponse;

  static equals(a: ListShortcutsResponse | PlainMessage<ListShortcutsResponse> | undefined, b: ListShortcutsResponse | PlainMessage<ListShortcutsResponse> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.GetShortcutRequest
 */
export declare class GetShortcutRequest extends Message<GetShortcutRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  constructor(data?: PartialMessage<GetShortcutRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.GetShortcutRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetShortcutRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetShortcutRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetShortcutRequest;

  static equals(a: GetShortcutRequest | PlainMessage<GetShortcutRequest> | undefined, b: GetShortcutRequest | PlainMessage<GetShortcutRequest> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.GetShortcutResponse
 */
export declare class GetShortcutResponse extends Message<GetShortcutResponse> {
  /**
   * @generated from field: slash.api.v2.Shortcut shortcut = 1;
   */
  shortcut?: Shortcut;

  constructor(data?: PartialMessage<GetShortcutResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.GetShortcutResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetShortcutResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetShortcutResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetShortcutResponse;

  static equals(a: GetShortcutResponse | PlainMessage<GetShortcutResponse> | undefined, b: GetShortcutResponse | PlainMessage<GetShortcutResponse> | undefined): boolean;
}

