// @generated by protoc-gen-es v1.3.0
// @generated from file api/v2/user_service.proto (package slash.api.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { RowStatus } from "./common_pb.js";

/**
 * @generated from enum slash.api.v2.Role
 */
export declare enum Role {
  /**
   * @generated from enum value: ROLE_UNSPECIFIED = 0;
   */
  ROLE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: ADMIN = 1;
   */
  ADMIN = 1,

  /**
   * @generated from enum value: USER = 2;
   */
  USER = 2,
}

/**
 * @generated from message slash.api.v2.User
 */
export declare class User extends Message<User> {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: slash.api.v2.RowStatus row_status = 2;
   */
  rowStatus: RowStatus;

  /**
   * @generated from field: int64 created_ts = 3;
   */
  createdTs: bigint;

  /**
   * @generated from field: int64 updated_ts = 4;
   */
  updatedTs: bigint;

  /**
   * @generated from field: slash.api.v2.Role role = 6;
   */
  role: Role;

  /**
   * @generated from field: string email = 7;
   */
  email: string;

  /**
   * @generated from field: string nickname = 8;
   */
  nickname: string;

  constructor(data?: PartialMessage<User>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.User";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): User;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): User;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): User;

  static equals(a: User | PlainMessage<User> | undefined, b: User | PlainMessage<User> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.GetUserRequest
 */
export declare class GetUserRequest extends Message<GetUserRequest> {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  constructor(data?: PartialMessage<GetUserRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.GetUserRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserRequest;

  static equals(a: GetUserRequest | PlainMessage<GetUserRequest> | undefined, b: GetUserRequest | PlainMessage<GetUserRequest> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.GetUserResponse
 */
export declare class GetUserResponse extends Message<GetUserResponse> {
  /**
   * @generated from field: slash.api.v2.User user = 1;
   */
  user?: User;

  constructor(data?: PartialMessage<GetUserResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.GetUserResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserResponse;

  static equals(a: GetUserResponse | PlainMessage<GetUserResponse> | undefined, b: GetUserResponse | PlainMessage<GetUserResponse> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.ListUserAccessTokensRequest
 */
export declare class ListUserAccessTokensRequest extends Message<ListUserAccessTokensRequest> {
  /**
   * id is the user id.
   *
   * @generated from field: int32 id = 1;
   */
  id: number;

  constructor(data?: PartialMessage<ListUserAccessTokensRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.ListUserAccessTokensRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListUserAccessTokensRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListUserAccessTokensRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListUserAccessTokensRequest;

  static equals(a: ListUserAccessTokensRequest | PlainMessage<ListUserAccessTokensRequest> | undefined, b: ListUserAccessTokensRequest | PlainMessage<ListUserAccessTokensRequest> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.ListUserAccessTokensResponse
 */
export declare class ListUserAccessTokensResponse extends Message<ListUserAccessTokensResponse> {
  /**
   * @generated from field: repeated slash.api.v2.UserAccessToken access_tokens = 1;
   */
  accessTokens: UserAccessToken[];

  constructor(data?: PartialMessage<ListUserAccessTokensResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.ListUserAccessTokensResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListUserAccessTokensResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListUserAccessTokensResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListUserAccessTokensResponse;

  static equals(a: ListUserAccessTokensResponse | PlainMessage<ListUserAccessTokensResponse> | undefined, b: ListUserAccessTokensResponse | PlainMessage<ListUserAccessTokensResponse> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.CreateUserAccessTokenRequest
 */
export declare class CreateUserAccessTokenRequest extends Message<CreateUserAccessTokenRequest> {
  /**
   * id is the user id.
   *
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: slash.api.v2.UserAccessToken user_access_token = 2;
   */
  userAccessToken?: UserAccessToken;

  constructor(data?: PartialMessage<CreateUserAccessTokenRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.CreateUserAccessTokenRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateUserAccessTokenRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateUserAccessTokenRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateUserAccessTokenRequest;

  static equals(a: CreateUserAccessTokenRequest | PlainMessage<CreateUserAccessTokenRequest> | undefined, b: CreateUserAccessTokenRequest | PlainMessage<CreateUserAccessTokenRequest> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.CreateUserAccessTokenResponse
 */
export declare class CreateUserAccessTokenResponse extends Message<CreateUserAccessTokenResponse> {
  /**
   * @generated from field: slash.api.v2.UserAccessToken access_token = 1;
   */
  accessToken?: UserAccessToken;

  constructor(data?: PartialMessage<CreateUserAccessTokenResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.CreateUserAccessTokenResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateUserAccessTokenResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateUserAccessTokenResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateUserAccessTokenResponse;

  static equals(a: CreateUserAccessTokenResponse | PlainMessage<CreateUserAccessTokenResponse> | undefined, b: CreateUserAccessTokenResponse | PlainMessage<CreateUserAccessTokenResponse> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.DeleteUserAccessTokenRequest
 */
export declare class DeleteUserAccessTokenRequest extends Message<DeleteUserAccessTokenRequest> {
  /**
   * id is the user id.
   *
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * access_token is the access token to delete.
   *
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  constructor(data?: PartialMessage<DeleteUserAccessTokenRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.DeleteUserAccessTokenRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteUserAccessTokenRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteUserAccessTokenRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteUserAccessTokenRequest;

  static equals(a: DeleteUserAccessTokenRequest | PlainMessage<DeleteUserAccessTokenRequest> | undefined, b: DeleteUserAccessTokenRequest | PlainMessage<DeleteUserAccessTokenRequest> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.DeleteUserAccessTokenResponse
 */
export declare class DeleteUserAccessTokenResponse extends Message<DeleteUserAccessTokenResponse> {
  constructor(data?: PartialMessage<DeleteUserAccessTokenResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.DeleteUserAccessTokenResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteUserAccessTokenResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteUserAccessTokenResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteUserAccessTokenResponse;

  static equals(a: DeleteUserAccessTokenResponse | PlainMessage<DeleteUserAccessTokenResponse> | undefined, b: DeleteUserAccessTokenResponse | PlainMessage<DeleteUserAccessTokenResponse> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.UserAccessToken
 */
export declare class UserAccessToken extends Message<UserAccessToken> {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: google.protobuf.Timestamp issued_at = 3;
   */
  issuedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 4;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<UserAccessToken>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.UserAccessToken";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserAccessToken;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserAccessToken;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserAccessToken;

  static equals(a: UserAccessToken | PlainMessage<UserAccessToken> | undefined, b: UserAccessToken | PlainMessage<UserAccessToken> | undefined): boolean;
}

