// @generated by protoc-gen-es v1.3.0
// @generated from file api/v2/shortcut_service.proto (package slash.api.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { RowStatus } from "./common_pb.js";

/**
 * @generated from enum slash.api.v2.Visibility
 */
export const Visibility = proto3.makeEnum(
  "slash.api.v2.Visibility",
  [
    {no: 0, name: "VISIBILITY_UNSPECIFIED"},
    {no: 1, name: "PRIVATE"},
    {no: 2, name: "WORKSPACE"},
    {no: 3, name: "PUBLIC"},
  ],
);

/**
 * @generated from message slash.api.v2.Shortcut
 */
export const Shortcut = proto3.makeMessageType(
  "slash.api.v2.Shortcut",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "creator_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "created_ts", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "updated_ts", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "row_status", kind: "enum", T: proto3.getEnumType(RowStatus) },
    { no: 6, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "tags", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 10, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "visibility", kind: "enum", T: proto3.getEnumType(Visibility) },
    { no: 12, name: "og_metadata", kind: "message", T: OpenGraphMetadata },
  ],
);

/**
 * @generated from message slash.api.v2.OpenGraphMetadata
 */
export const OpenGraphMetadata = proto3.makeMessageType(
  "slash.api.v2.OpenGraphMetadata",
  () => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message slash.api.v2.ListShortcutsRequest
 */
export const ListShortcutsRequest = proto3.makeMessageType(
  "slash.api.v2.ListShortcutsRequest",
  [],
);

/**
 * @generated from message slash.api.v2.ListShortcutsResponse
 */
export const ListShortcutsResponse = proto3.makeMessageType(
  "slash.api.v2.ListShortcutsResponse",
  () => [
    { no: 1, name: "shortcuts", kind: "message", T: Shortcut, repeated: true },
  ],
);

/**
 * @generated from message slash.api.v2.GetShortcutRequest
 */
export const GetShortcutRequest = proto3.makeMessageType(
  "slash.api.v2.GetShortcutRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message slash.api.v2.GetShortcutResponse
 */
export const GetShortcutResponse = proto3.makeMessageType(
  "slash.api.v2.GetShortcutResponse",
  () => [
    { no: 1, name: "shortcut", kind: "message", T: Shortcut },
  ],
);

/**
 * @generated from message slash.api.v2.CreateShortcutRequest
 */
export const CreateShortcutRequest = proto3.makeMessageType(
  "slash.api.v2.CreateShortcutRequest",
  () => [
    { no: 1, name: "shortcut", kind: "message", T: Shortcut },
  ],
);

/**
 * @generated from message slash.api.v2.CreateShortcutResponse
 */
export const CreateShortcutResponse = proto3.makeMessageType(
  "slash.api.v2.CreateShortcutResponse",
  () => [
    { no: 1, name: "shortcut", kind: "message", T: Shortcut },
  ],
);

