// @generated by protoc-gen-es v1.3.0
// @generated from file api/v2/common.proto (package slash.api.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum slash.api.v2.RowStatus
 */
export const RowStatus = proto3.makeEnum(
  "slash.api.v2.RowStatus",
  [
    {no: 0, name: "ROW_STATUS_UNSPECIFIED"},
    {no: 1, name: "NORMAL"},
    {no: 2, name: "ARCHIVED"},
  ],
);

