// @generated by protoc-gen-es v1.3.0
// @generated from file api/v2/user_setting_service.proto (package slash.api.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message slash.api.v2.UserSetting
 */
export declare class UserSetting extends Message<UserSetting> {
  /**
   * id is the user id.
   *
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * locale is the user locale.
   *
   * @generated from field: slash.api.v2.UserSetting.Locale locale = 2;
   */
  locale: UserSetting_Locale;

  /**
   * color_theme is the user color theme.
   *
   * @generated from field: slash.api.v2.UserSetting.ColorTheme color_theme = 3;
   */
  colorTheme: UserSetting_ColorTheme;

  constructor(data?: PartialMessage<UserSetting>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.UserSetting";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserSetting;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserSetting;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserSetting;

  static equals(a: UserSetting | PlainMessage<UserSetting> | undefined, b: UserSetting | PlainMessage<UserSetting> | undefined): boolean;
}

/**
 * @generated from enum slash.api.v2.UserSetting.Locale
 */
export declare enum UserSetting_Locale {
  /**
   * @generated from enum value: LOCALE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LOCALE_EN = 1;
   */
  EN = 1,

  /**
   * @generated from enum value: LOCALE_ZH = 2;
   */
  ZH = 2,
}

/**
 * @generated from enum slash.api.v2.UserSetting.ColorTheme
 */
export declare enum UserSetting_ColorTheme {
  /**
   * @generated from enum value: COLOR_THEME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: COLOR_THEME_LIGHT = 1;
   */
  LIGHT = 1,

  /**
   * @generated from enum value: COLOR_THEME_DARK = 2;
   */
  DARK = 2,
}

/**
 * @generated from message slash.api.v2.GetUserSettingRequest
 */
export declare class GetUserSettingRequest extends Message<GetUserSettingRequest> {
  /**
   * id is the user id.
   *
   * @generated from field: int32 id = 1;
   */
  id: number;

  constructor(data?: PartialMessage<GetUserSettingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.GetUserSettingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserSettingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserSettingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserSettingRequest;

  static equals(a: GetUserSettingRequest | PlainMessage<GetUserSettingRequest> | undefined, b: GetUserSettingRequest | PlainMessage<GetUserSettingRequest> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.GetUserSettingResponse
 */
export declare class GetUserSettingResponse extends Message<GetUserSettingResponse> {
  /**
   * @generated from field: slash.api.v2.UserSetting user_setting = 1;
   */
  userSetting?: UserSetting;

  constructor(data?: PartialMessage<GetUserSettingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.GetUserSettingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserSettingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserSettingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserSettingResponse;

  static equals(a: GetUserSettingResponse | PlainMessage<GetUserSettingResponse> | undefined, b: GetUserSettingResponse | PlainMessage<GetUserSettingResponse> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.UpdateUserSettingRequest
 */
export declare class UpdateUserSettingRequest extends Message<UpdateUserSettingRequest> {
  /**
   * id is the user id.
   *
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * user_setting is the user setting to update.
   *
   * @generated from field: slash.api.v2.UserSetting user_setting = 2;
   */
  userSetting?: UserSetting;

  /**
   * update_mask is the field mask to update.
   *
   * @generated from field: repeated string update_mask = 3;
   */
  updateMask: string[];

  constructor(data?: PartialMessage<UpdateUserSettingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.UpdateUserSettingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateUserSettingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateUserSettingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateUserSettingRequest;

  static equals(a: UpdateUserSettingRequest | PlainMessage<UpdateUserSettingRequest> | undefined, b: UpdateUserSettingRequest | PlainMessage<UpdateUserSettingRequest> | undefined): boolean;
}

/**
 * @generated from message slash.api.v2.UpdateUserSettingResponse
 */
export declare class UpdateUserSettingResponse extends Message<UpdateUserSettingResponse> {
  /**
   * @generated from field: slash.api.v2.UserSetting user_setting = 1;
   */
  userSetting?: UserSetting;

  constructor(data?: PartialMessage<UpdateUserSettingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.api.v2.UpdateUserSettingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateUserSettingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateUserSettingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateUserSettingResponse;

  static equals(a: UpdateUserSettingResponse | PlainMessage<UpdateUserSettingResponse> | undefined, b: UpdateUserSettingResponse | PlainMessage<UpdateUserSettingResponse> | undefined): boolean;
}

