// @generated by protoc-gen-es v1.3.0
// @generated from file api/v2/user_setting_service.proto (package slash.api.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message slash.api.v2.UserSetting
 */
export const UserSetting = proto3.makeMessageType(
  "slash.api.v2.UserSetting",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "locale", kind: "enum", T: proto3.getEnumType(UserSetting_Locale) },
  ],
);

/**
 * @generated from enum slash.api.v2.UserSetting.Locale
 */
export const UserSetting_Locale = proto3.makeEnum(
  "slash.api.v2.UserSetting.Locale",
  [
    {no: 0, name: "LOCALE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "LOCALE_EN", localName: "EN"},
    {no: 2, name: "LOCALE_ZH", localName: "ZH"},
  ],
);

/**
 * @generated from message slash.api.v2.GetUserSettingRequest
 */
export const GetUserSettingRequest = proto3.makeMessageType(
  "slash.api.v2.GetUserSettingRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message slash.api.v2.GetUserSettingResponse
 */
export const GetUserSettingResponse = proto3.makeMessageType(
  "slash.api.v2.GetUserSettingResponse",
  () => [
    { no: 1, name: "user_setting", kind: "message", T: UserSetting },
  ],
);

/**
 * @generated from message slash.api.v2.UpdateUserSettingRequest
 */
export const UpdateUserSettingRequest = proto3.makeMessageType(
  "slash.api.v2.UpdateUserSettingRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "user_setting", kind: "message", T: UserSetting },
    { no: 3, name: "update_mask", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message slash.api.v2.UpdateUserSettingResponse
 */
export const UpdateUserSettingResponse = proto3.makeMessageType(
  "slash.api.v2.UpdateUserSettingResponse",
  () => [
    { no: 1, name: "user_setting", kind: "message", T: UserSetting },
  ],
);

