// @generated by protoc-gen-es v1.3.0
// @generated from file store/common.proto (package slash.store, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from enum slash.store.RowStatus
 */
export declare enum RowStatus {
  /**
   * @generated from enum value: ROW_STATUS_UNSPECIFIED = 0;
   */
  ROW_STATUS_UNSPECIFIED = 0,

  /**
   * @generated from enum value: NORMAL = 1;
   */
  NORMAL = 1,

  /**
   * @generated from enum value: ARCHIVED = 2;
   */
  ARCHIVED = 2,
}

