// @generated by protoc-gen-es v1.3.0
// @generated from file store/shortcut.proto (package slash.store, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { RowStatus } from "./common_pb.js";

/**
 * @generated from enum slash.store.Visibility
 */
export const Visibility = proto3.makeEnum(
  "slash.store.Visibility",
  [
    {no: 0, name: "VISIBILITY_UNSPECIFIED"},
    {no: 1, name: "PRIVATE"},
    {no: 2, name: "WORKSPACE"},
    {no: 3, name: "PUBLIC"},
  ],
);

/**
 * @generated from message slash.store.Shortcut
 */
export const Shortcut = proto3.makeMessageType(
  "slash.store.Shortcut",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "creator_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "created_ts", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "updated_ts", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "row_status", kind: "enum", T: proto3.getEnumType(RowStatus) },
    { no: 6, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "tags", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 10, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "visibility", kind: "enum", T: proto3.getEnumType(Visibility) },
    { no: 12, name: "og_metadata", kind: "message", T: OpenGraphMetadata },
  ],
);

/**
 * @generated from message slash.store.OpenGraphMetadata
 */
export const OpenGraphMetadata = proto3.makeMessageType(
  "slash.store.OpenGraphMetadata",
  () => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

