// @generated by protoc-gen-es v1.3.0
// @generated from file store/workspace_setting.proto (package slash.store, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum slash.store.WorkspaceSettingKey
 */
export declare enum WorkspaceSettingKey {
  /**
   * @generated from enum value: WORKSPACE_SETTING_KEY_UNSPECIFIED = 0;
   */
  WORKSPACE_SETTING_KEY_UNSPECIFIED = 0,

  /**
   * The secret session key used to encrypt session data.
   *
   * @generated from enum value: WORKSPACE_SETTING_SECRET_SESSION = 1;
   */
  WORKSPACE_SETTING_SECRET_SESSION = 1,

  /**
   * Whether to enable other users to sign up.
   *
   * @generated from enum value: WORKSAPCE_SETTING_ENABLE_SIGNUP = 2;
   */
  WORKSAPCE_SETTING_ENABLE_SIGNUP = 2,

  /**
   * The relative path of the resource directory.
   *
   * @generated from enum value: WORKSPACE_SETTING_RESOURCE_RELATIVE_PATH = 3;
   */
  WORKSPACE_SETTING_RESOURCE_RELATIVE_PATH = 3,

  /**
   * The auto backup setting.
   *
   * @generated from enum value: WORKSPACE_SETTING_AUTO_BACKUP = 4;
   */
  WORKSPACE_SETTING_AUTO_BACKUP = 4,
}

/**
 * @generated from message slash.store.WorkspaceSetting
 */
export declare class WorkspaceSetting extends Message<WorkspaceSetting> {
  /**
   * @generated from field: slash.store.WorkspaceSettingKey key = 1;
   */
  key: WorkspaceSettingKey;

  /**
   * @generated from oneof slash.store.WorkspaceSetting.value
   */
  value: {
    /**
     * @generated from field: string secret_session = 2;
     */
    value: string;
    case: "secretSession";
  } | {
    /**
     * @generated from field: bool enable_signup = 3;
     */
    value: boolean;
    case: "enableSignup";
  } | {
    /**
     * @generated from field: string resource_relative_path = 4;
     */
    value: string;
    case: "resourceRelativePath";
  } | {
    /**
     * @generated from field: slash.store.AutoBackupWorkspaceSetting auto_backup = 5;
     */
    value: AutoBackupWorkspaceSetting;
    case: "autoBackup";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<WorkspaceSetting>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.store.WorkspaceSetting";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): WorkspaceSetting;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): WorkspaceSetting;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): WorkspaceSetting;

  static equals(a: WorkspaceSetting | PlainMessage<WorkspaceSetting> | undefined, b: WorkspaceSetting | PlainMessage<WorkspaceSetting> | undefined): boolean;
}

/**
 * @generated from message slash.store.AutoBackupWorkspaceSetting
 */
export declare class AutoBackupWorkspaceSetting extends Message<AutoBackupWorkspaceSetting> {
  /**
   * Whether auto backup is enabled.
   *
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * The cron expression for auto backup.
   * For example, "0 0 0 * * *" means backup at 00:00:00 every day.
   * See https://en.wikipedia.org/wiki/Cron for more details.
   *
   * @generated from field: string cron_expression = 2;
   */
  cronExpression: string;

  /**
   * The maximum number of backups to keep.
   *
   * @generated from field: int32 max_keep = 3;
   */
  maxKeep: number;

  constructor(data?: PartialMessage<AutoBackupWorkspaceSetting>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "slash.store.AutoBackupWorkspaceSetting";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AutoBackupWorkspaceSetting;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AutoBackupWorkspaceSetting;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AutoBackupWorkspaceSetting;

  static equals(a: AutoBackupWorkspaceSetting | PlainMessage<AutoBackupWorkspaceSetting> | undefined, b: AutoBackupWorkspaceSetting | PlainMessage<AutoBackupWorkspaceSetting> | undefined): boolean;
}

