// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: api/v1/common.proto

/* eslint-disable */

export const protobufPackage = "slash.api.v1";

export enum State {
  STATE_UNSPECIFIED = "STATE_UNSPECIFIED",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function stateFromJSON(object: any): State {
  switch (object) {
    case 0:
    case "STATE_UNSPECIFIED":
      return State.STATE_UNSPECIFIED;
    case 1:
    case "ACTIVE":
      return State.ACTIVE;
    case 2:
    case "INACTIVE":
      return State.INACTIVE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return State.UNRECOGNIZED;
  }
}

export function stateToNumber(object: State): number {
  switch (object) {
    case State.STATE_UNSPECIFIED:
      return 0;
    case State.ACTIVE:
      return 1;
    case State.INACTIVE:
      return 2;
    case State.UNRECOGNIZED:
    default:
      return -1;
  }
}

export enum Visibility {
  VISIBILITY_UNSPECIFIED = "VISIBILITY_UNSPECIFIED",
  WORKSPACE = "WORKSPACE",
  PUBLIC = "PUBLIC",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function visibilityFromJSON(object: any): Visibility {
  switch (object) {
    case 0:
    case "VISIBILITY_UNSPECIFIED":
      return Visibility.VISIBILITY_UNSPECIFIED;
    case 1:
    case "WORKSPACE":
      return Visibility.WORKSPACE;
    case 2:
    case "PUBLIC":
      return Visibility.PUBLIC;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Visibility.UNRECOGNIZED;
  }
}

export function visibilityToNumber(object: Visibility): number {
  switch (object) {
    case Visibility.VISIBILITY_UNSPECIFIED:
      return 0;
    case Visibility.WORKSPACE:
      return 1;
    case Visibility.PUBLIC:
      return 2;
    case Visibility.UNRECOGNIZED:
    default:
      return -1;
  }
}
