// @generated by protoc-gen-es v1.3.0
// @generated from file store/user_setting.proto (package slash.store, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum slash.store.UserSettingKey
 */
export const UserSettingKey = proto3.makeEnum(
  "slash.store.UserSettingKey",
  [
    {no: 0, name: "USER_SETTING_KEY_UNSPECIFIED"},
    {no: 1, name: "USER_SETTING_ACCESS_TOKENS"},
    {no: 2, name: "USER_SETTING_LOCALE"},
  ],
);

/**
 * @generated from enum slash.store.LocaleUserSetting
 */
export const LocaleUserSetting = proto3.makeEnum(
  "slash.store.LocaleUserSetting",
  [
    {no: 0, name: "LOCALE_USER_SETTING_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "LOCALE_USER_SETTING_EN", localName: "EN"},
    {no: 2, name: "LOCALE_USER_SETTING_ZH", localName: "ZH"},
  ],
);

/**
 * @generated from message slash.store.UserSetting
 */
export const UserSetting = proto3.makeMessageType(
  "slash.store.UserSetting",
  () => [
    { no: 1, name: "user_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "key", kind: "enum", T: proto3.getEnumType(UserSettingKey) },
    { no: 3, name: "access_tokens", kind: "message", T: AccessTokensUserSetting, oneof: "value" },
    { no: 4, name: "locale", kind: "enum", T: proto3.getEnumType(LocaleUserSetting), oneof: "value" },
  ],
);

/**
 * @generated from message slash.store.AccessTokensUserSetting
 */
export const AccessTokensUserSetting = proto3.makeMessageType(
  "slash.store.AccessTokensUserSetting",
  () => [
    { no: 1, name: "access_tokens", kind: "message", T: AccessTokensUserSetting_AccessToken, repeated: true },
  ],
);

/**
 * @generated from message slash.store.AccessTokensUserSetting.AccessToken
 */
export const AccessTokensUserSetting_AccessToken = proto3.makeMessageType(
  "slash.store.AccessTokensUserSetting.AccessToken",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AccessTokensUserSetting_AccessToken"},
);

