// @generated by protoc-gen-es v1.3.0
// @generated from file store/workspace_setting.proto (package slash.store, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum slash.store.WorkspaceSettingKey
 */
export const WorkspaceSettingKey = proto3.makeEnum(
  "slash.store.WorkspaceSettingKey",
  [
    {no: 0, name: "WORKSPACE_SETTING_KEY_UNSPECIFIED"},
    {no: 1, name: "WORKSPACE_SETTING_AUTO_BACKUP"},
  ],
);

/**
 * @generated from message slash.store.WorkspaceSetting
 */
export const WorkspaceSetting = proto3.makeMessageType(
  "slash.store.WorkspaceSetting",
  () => [
    { no: 1, name: "key", kind: "enum", T: proto3.getEnumType(WorkspaceSettingKey) },
    { no: 2, name: "auto_backup", kind: "message", T: AutoBackupWorkspaceSetting, oneof: "value" },
  ],
);

/**
 * @generated from message slash.store.AutoBackupWorkspaceSetting
 */
export const AutoBackupWorkspaceSetting = proto3.makeMessageType(
  "slash.store.AutoBackupWorkspaceSetting",
  () => [
    { no: 1, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "cron_expression", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "max_keep", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

