// @generated by protoc-gen-es v1.3.0
// @generated from file store/activity.proto (package slash.store, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message slash.store.ActivityShorcutCreatePayload
 */
export const ActivityShorcutCreatePayload = proto3.makeMessageType(
  "slash.store.ActivityShorcutCreatePayload",
  () => [
    { no: 1, name: "shortcut_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

